# Generated by Django 5.1.6 on 2025-05-03 07:05

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=posts.models.path_and_rename, verbose_name='Image'),
        ),
    ]
