# Generated by Django 5.1.6 on 2025-06-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='background',
            new_name='local_background',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='background',
            new_name='global_background',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Display Name'),
        ),
    ]
