# Generated by Django 5.1.6 on 2025-06-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('background', models.TextField(blank=True, default='', verbose_name='Background')),
            ],
            options={
                'permissions': [('can_manage_organization', 'Can manage this organization'), ('can_edit_organization', 'Can edit organization details'), ('can_delete_organization', 'Can delete this organization'), ('can_invite_members', 'Can invite members to organization'), ('can_post_in_organization', 'Can post in this organization')],
            },
        ),
    ]
