# Generated by Django 5.1.6 on 2025-06-11 04:20

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('posts', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='postlocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.postlocation', verbose_name='Location'),
        ),
    ]
