# Generated by Django 5.1.6 on 2025-06-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_posttemplate_location'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.DeleteModel(
            name='PostLocation',
        ),
    ]
