name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff check
        run: ruff check . --output-format=github --exit-zero

      - name: Run ruff fix
        run: ruff check . --fix --exit-zero

      - name: Commit and push ruff fixes
        if: success()
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: auto-fix ruff issues"
            git push
          fi
